s = open('24-239.txt').readline()

#s = 'ZZXZXZZXYYZYZZYYY'

#s = "XYYZZYZZYZYZXYXYXYYZYZZXYXYYZZYZZXYYZZYZZXYYZXYYZYZYZYZXYYZZYZZXYYZYZZYZXYXYZZYZXYYZZYZYZYZZYZYZZYZXYYZXYYZZYZZXYYZZYZYZZYZZYZZXYYZYZZYZZYZZYZZYZZXYYZZYZYZZXYYZZYZZYZYZZXYYZZXYYZZXYZYZZYZZXYYZZXYYZZXYYZZYZYZYZYZZXYYZXYXYYZXYXYZXYYZXYXYXYZZYZZYZYZYZYZYZYZXYYZYZXYYZZYZYZZYZXYYZYZZYZZYZYZZYZZYZZXYYZZXYXYYZYZZYZZXYXYZZYZYZZYZYZXYXYXYYZYZZYZZXYYZZYZZYZZXYYZYZZXYYZXYXYYZZXYXYYZXYYZYZYZZYZYZZYZXYYZZXYXYXYZZYZZYZZXYXYYZYZZXYYZZXYYZYZYZZXYYZXYYZZYZXYYZZYZZXYZYZZYZZXYYZYZYZZYZYZZYZZYZZYZXYXY"

s = '.' + s
N = len(s)
dp = [0]*(N+1)
for i in range(2,N-2):
  if s[i-1:i+1] in ['XY', 'YZ']:
    dp[i] = dp[i-2] + 2
  if s[i-2:i+1] in ['YZZ']:
    dp[i] = max( dp[i], dp[i-3] + 3 )

print( max(dp) )
